rsv-ink/ink_components

- app/components/ink_components/attribute_merger.rb
Issue #9 
Implementa a classe `AttributeMerger` que permite concatenar os elementos de dois hashes pelas chaves. Exemplo:
```ruby
object1 = { list: [1, 2, 3], class: "bg-blue-500", child: { name: "child" } }
object2 = { list: [4, 5, 6], class: "text-blue-500", child: { name: "1" } }
atributte_merger = AttributeMerger.new(default_attributes: object1, user_attributes: object2)
attribute_merger.merge
```
> feat: Implementa a classe AttributeMerger

- app/components/ink_components/forms/checkbox/component.html.erb
- app/components/ink_components/forms/checkbox/component.rb
A partir da versão 7.1.3.2 do Rails, os parâmetros do método check_box_tag mudaram:
```
- check_box_tag(name, value = "1", checked = false, options = {})
+ check_box_tag(name, *args)
```
Dessa forma, as classes do componente Checkbox não estão sendo renderizadas corretamente em aplicações Rails 6.1.0. Para resolver esse problema, precisamos adicionar o parâmetro `checked` explicitamente, uma vez que o mesmo estava sendo passado via `extra_attributes`.
**Lookbook do Monolito:**
> fix: Corrige parâmetros do componente Checkbox

- app/helpers/ink_components/form_builder.rb
- app/views/users/new.html.erb
- spec/dummy/app/controllers/users_controller.rb
- spec/dummy/app/models/user.rb
O helper `radio_button` gera uma tag de botão de rádio que permite acessar um atributo específico de um objeto atribuído ao template. Caso o valor atual do método corresponda a `value`, o botão de rádio será marcado. Esse helper está em conformidade com a interface do Rails.
Exemplo:
```ruby
radio_button("article", "category", "rails") # esse radio será marcado
radio_button("article", "category", "java")
```
https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-radio_button
> feat: Cria helper radio_button para o Form Builder

- app/helpers/ink_components/form_builder.rb
- app/views/users/new.html.erb
Implementei o helper `select` para simplificar a utilização do componente em formulários. Esse método mantém a mesma interface do Rails, facilitando a transição para o Form Builder. Ele aceita os seguintes parâmetros:
- `attribute`: representa o atributo do modelo.
-  `choices`: lista de opções disponíveis para seleção, equivalente a `options` no componente.
- `select_options`: configurações específicas para campos select, como `prompt` e `include_blank`.
- `tag_options`: opções HTML adicionais, como `data_attributes` e `class`, correspondendo a `extra_attributes` no componente.
Obs: O helper `select` do Rails tem a possibilidade de receber um bloco, esse comportamento será implementado em nosso componente em uma próxima atividade. …
> feat: Cria helper select para Form Builder

- app/helpers/ink_components/form_builder.rb
- spec/dummy/app/models/user.rb
Implementei o helper `submit` para renderizar um componente de botão personalizado, especificamente destinado à submissão de formulários. Este método preserva a mesma interface do Rails, o que facilita a transição para o Form Builder. Ele aceita os seguintes parâmetros:
-  `content`: O texto ou conteúdo a ser exibido no botão.
-  `kwargs`: Permite a inclusão de quaisquer atributos HTML, além de parâmetros específicos do componente, como `size: :sm`.
https://apidock.com/rails/v7.1.3.4/ActionView/Helpers/FormBuilder/submit
> feat: Cria helper submit para Form Builder

- app/components/ink_components/forms/select/component.html.erb
- app/components/ink_components/forms/select/component.rb
- app/components/ink_components/forms/select/preview.rb
- app/helpers/ink_components/form_builder.rb
- app/views/users/new.html.erb
- spec/components/ink_components/forms/select_component_spec.rb
Atualmente, nosso componente `select` não está configurado para aceitar um bloco. Contudo, a interface helper no Form Builder do Rails suporta o uso de blocos. Portanto, precisamos realizar os ajustes necessários para garantir que nosso helper esteja alinhado com os padrões do Rails.
> fix: Permite que um bloco seja passado ao componente Select

- app/components/ink_components/badge/component.rb
- app/components/ink_components/button/component.rb
- app/components/ink_components/button/preview.rb
Os componentes `button` e `badge` tem classes `me-2` e `mb-2` presentes que adicionam margens extras nesses componentes. Essas margens não deveriam estar presentes. Este PR remove as classes `me-2` e `mb-2` e define o `builder` default do button para `button_tag`.
**Componente Button:**
**Componente Badge:**
> feat: Remove as margens desnecessárias dos componentes button e badge

- app/components/ink_components/forms/checkbox/component.html.erb
- app/components/ink_components/forms/checkbox/preview.rb
- spec/components/ink_components/forms/checkbox_component_spec.rb
O checkbox content adiciona uma div extra ao html mesmo quando não recebe um content ou helper_text. Isso acontece com usos legitimos como:
```erb
<%= form.check_box :name %>
<%= form.label :name %>
```
> fix: corrige checkbox quando não recebe content ou helper_text

- Gemfile.lock
- app/components/ink_components/modal/preview.rb
- lib/ink_components/version.rb
Este PR corrige o erro que estava acontecendo nos previews do componente `Modal`. O erro era o seguinte:
O erro acontecia quando um `content_tag` era usado dentro do bloco de algum slot. A correção consistiu em substituir os content_tags por `component_name.content_tag`.
- Corrige o erro nos previews do componente `Modal`
- Atualiza a versão da gem para `1.2.1`
> fix: Corrige os previews do componente modal

- Gemfile.lock
- app/components/ink_components/modal/component.html.erb
- app/components/ink_components/modal/component.rb
- app/components/ink_components/modal/header/component.html.erb
- app/components/ink_components/modal/header/component.rb
- app/components/ink_components/modal/preview.rb
- lib/ink_components/version.rb
- spec/components/ink_components/modal_component_spec.rb
**Mudanças**
- Adiciona a opção de incluir um **subtítulo** no modal.
- Refatoração do tratamento de responsividade: Removemos o uso de style inline, permitindo classes Tailwind como: `w-[345px]` e `md:w-[678px]`. Essa alteração foi feita porque a implementação anterior não permitia definir tamanhos específicos para diferentes tamanhos de tela, prejudicando a responsividade do modal.
- Atualiza a versão da gem para 2.0.0.
> feat: Adiciona novas funcionalidades ao Modal

- app/components/ink_components/application_component.rb
- app/components/ink_components/modal/component.rb
Adiciona o parâmetro `wrapper_attributes` para permitir passar atributos para a div mais externa do modal.
> feat: Adiciona o parâmetro wrapper_attributes

- app/components/ink_components/table/component.rb
- app/components/ink_components/table/preview.rb
Devido à classe relative aplicada à div wrapper da tabela, não foi possível usar componentes como o dropdown. Além disso, adicionei novas opções de sombras.
> fix: corrige problema com dropdown em tabelas

- app/components/ink_components/button/component.rb
O objetivo deste PR é corrigir a cor do `ring` do botão com shape `outline`. Atualmente os botões com shape `outline` aparecem com um `ring` de cor azul quando deveriam seguir a cor que o usuário definiu durante a inicialização do componente.
**Antes:**
**Depois:**
> fix: Corrige a cor do ring do botão outline

- app/components/ink_components/breadcrumb/component.html.erb
- app/components/ink_components/breadcrumb/component.rb
- app/components/ink_components/breadcrumb/list/component.html.erb
- app/components/ink_components/breadcrumb/list/component.rb
- app/components/ink_components/breadcrumb/list/item/component.html.erb
- app/components/ink_components/breadcrumb/list/item/component.rb
- app/components/ink_components/breadcrumb/preview.rb
- app/views/previews/ink_components/breadcrumb/background_solid.html.erb
- app/views/previews/ink_components/breadcrumb/background_transparent.html.erb
- app/views/previews/ink_components/breadcrumb/items_with_icons.html.erb
- app/views/previews/ink_components/breadcrumb/playground.html.erb
- spec/components/ink_components/breadcrumb_component_spec.rb
Capturas de tela do preview:
Exemplos:
Playground:
> feat: adiciona componente Breadcrumb com suporte a links e icones

- app/components/ink_components/icon/component.html.erb
- app/components/ink_components/icon/component.rb
- spec/components/ink_components/icon_component_spec.rb
Ao tentar renderizar um icone que não existe o component ainda renderiza um svg vazio o que gerá quebra de layouts. Com isso, iremos gerar um erro para indicar que este icone não existe estimulando o dev a corrigir o error.
> fix: adiciona validação de renderização em icones

- app/components/ink_components/skeleton/component.html.erb
- app/components/ink_components/skeleton/component.rb
- app/components/ink_components/skeleton/node_component.rb
- app/components/ink_components/skeleton/preview.rb
- app/views/previews/ink_components/skeleton/image_placeholder.html.erb
- app/views/previews/ink_components/skeleton/playground.html.erb
- spec/components/ink_components/skeleton_component_spec.rb
Implementa o componente [Skeleton](https://flowbite.com/docs/components/skeleton/):
**Playground:**
**Exemplo de skeleton para placeholder de imagem:**
> feat: Implementa o componente Skeleton

- app/components/ink_components/modal/header/close_button/component.html.erb
- app/components/ink_components/modal/header/close_button/component.rb
- app/components/ink_components/modal/header/component.html.erb
- app/components/ink_components/modal/header/component.rb
- app/components/ink_components/modal/preview.rb
Para dar mais flexibilidade para usarmos o stimulus, decidi por colocar o close button do header do modal como slot. Isso, nos abre a possibilidade de personalizar mais como fechar o modal.
> feat: adiciona o close button do modal como slot

- app/components/ink_components/application_component.rb
- app/components/ink_components/helpers.rb
O construtor do `ApplicationComponent` cria uma instância do TailwindMerger e AttributeMerger sempre que é invocado. Essas instâncias adicionam overhead na renderização dos componentes.
Move a inicialização do TailwindMerger para uma constante e move a lógica do AttributeMerger para um helper.
**Antes:**
**Depois:**
<details>
<summary>
Script do benchmark
</summary>
```ruby
require_relative 'config/environment'
require 'benchmark/ips'
class DummyComponent < InkComponents::ApplicationComponent
def default_attrs
{ class: "bg-white text-black" }
end
end
Benchmark.ips do |x|
x.config(time: 5, warmup: 2)
x.report("basic init") do
DummyComponent.new
end
x.report("init with class") do
DummyComponent.new(class: "bg-red-500 text-white")
end
x.report("init with mixed attrs") do …
```
> refactor: Move o tailwind merger para uma constante

- app/components/ink_components/popover/component.rb
- app/components/ink_components/popover/preview.rb
Este pull request corrige a exibição da seta no componente popover. Foram realizadas pequenas alterações nos arquivos para garantir que o componente seja exibido corretamente.
Foi adicionado o `data-popover` por padrão nos atributos do componente, com essa adição a seta funciona conforme o esperado.
Tambem foi alterado o arquivo de preview, pois ele contia um bug. O `component` estava sendo chamado de forma incorreta no preview `popover_company_profile`
Antes:
Depois:
> fix: corrige a exibição da seta no componente popover

- Gemfile.lock
- lib/ink_components/version.rb
Correções dessa atualização:
[fix: corrige a exibição da seta no componente popover](https://github.com/rsv-ink/ink_components/pull/155)
> upgrade: atualiza a versão do ink_components para 4.1.1

- app/components/ink_components/accordion/component.rb
- app/components/ink_components/accordion/preview.rb
Este *pull request* aprimora o componente `Accordion` na biblioteca `ink_components` ao introduzir um novo estilo `flush` com variantes de cor, atualizando a lógica de inicialização para definir uma cor padrão e melhorando o tratamento das classes ativas/inativas para o estilo `flush`. Além disso, modifica o método de *preview* do `flush` para suportar a seleção de cor.
* Adicionado um novo estilo `flush` com variantes de cor para os estados ativo e inativo, com suporte para as cores: `pink`, `blue`, `red`, `green`, `purple`, `orange`, `yellow` e `gray`.
* Atualizado o método `default_attributes` para atribuir dinamicamente `data-active-classes` e `data-inactive-classes` com base no estilo `flush` e na cor selecionada.
* Remove o método `tap` para ajustar o merge dos atrributos vindo do …
> refactor: Adiciona color variants para accordion flush

- .tool-versions
- app/components/ink_components/icon/preview.rb
- app/views/previews/ink_components/icon/outline.html.erb
- app/views/previews/ink_components/icon/solid.html.erb
Quando um icone não é encontrado ele gera um error. Contudo, com isso não conseguimos visualizar todos os icones no modo preview, pois mostramos os dois tipos de icones juntos, mas não quer dizer que vá exister os dois sempre.
> fix: corrige renderização de icones no preview
